# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera_type',
            field=models.CharField(choices=[('pinhole', 'Pinhole'), ('fuji', 'Fuji'), ('nikon', 'Nikon'), ('canon', 'Canon'), ('sony', 'Sony'), ('hasselblad', 'Hasselblad'), ('iphone', 'iPhone'), ('analog slr', 'analog SLR'), ('analog rangefinder', 'analog rangefinder'), ('medium format', 'medium format'), ('funsnap', 'Funsnap')], default='pinhole', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='personal_website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photography_type',
            field=models.CharField(choices=[('studio', 'Studio'), ('portraiture', 'Portraiture'), ('news_documentary', 'News/Documentary'), ('street photography', 'Street Photography'), ('weddings_events', 'Weddings and Events'), ('erotica', 'Erotica'), ('sports', 'Sports'), ('product', 'Product Photography')], default='selfies', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='travel_radius',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
