# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0003_auto_20170117_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='photography_type',
            field=models.CharField(choices=[('studio', 'Studio'), ('portraiture', 'Portraiture'), ('news_documentary', 'News/Documentary'), ('street photography', 'Street Photography'), ('weddings_events', 'Weddings and Events'), ('erotica', 'Erotica'), ('sports', 'Sports'), ('product', 'Product Photography')], default='selfies', max_length=255),
        ),
    ]
