# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0004_auto_20170120_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
