# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20170123_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='albums',
            field=models.ManyToManyField(blank=True, to='imager_images.Album'),
        ),
    ]
