# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20170123_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.FilePathField(path='/Users/CCallahanIV/Documents/CodeFellows/401/assignments/week6/django-imager/imagersite/MEDIA'),
        ),
    ]
