# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0006_auto_20170123_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='albums',
        ),
        migrations.AddField(
            model_name='album',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='album', to='imager_images.Photo'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='imager_images.Photo'),
        ),
    ]
